on:
  # Trigger the workflow on push or pull request
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This repository is no longer maintained and no longer used in our company\nIf you depend on it or need adaptations (like compatibility updates) please fork it.\n'
            })
